[package]
name = "shadercrab"
version = "0.1.0"
description = "A simple single buffer shadertoy emulator"
licence = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"